test:
  database: meltdown-test
  host: localhost
  port: 27017
  websocket_channel: magent.websocket

development:
  database: meltdown-development
  host: localhost
  port: 27017
  websocket_channel: magent.websocket

production:
  database: meltdown-production
  websocket_channel: magent.websocket

