development:
  database: shapado-development
  host: localhost
  port: 27017
  websocket_channel: magent.websocket

test:
  database: shapado-test

production:
  database: shapado-production
  websocket_channel: magent.websocket

